### ISSUE TITLE
更新适配Typecho1.2.1？

### ISSUE THREAD

**Issue by huarzone** [benzBrake/AutoBackup#1]
更新适配Typecho1.2.1？

**Comment by benzBrake** [comment]
不是能用吗？我一直都在用的啊

**Comment by huarzone** [comment]
> 不是能用吗？我一直都在用的啊

你的是 Typecho 1.2.1版本吗？

**Comment by benzBrake** [comment]
> > 不是能用吗？我一直都在用的啊
> 
> 你的是 Typecho 1.2.1版本吗？

当然是 1.2.1 啊，你手动访问接口自己检查为啥报错吧
